version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command:
      - flask
      - run
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app/
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}